version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.1.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run: 
        name: Build and run tests
        command: fastlane scan
        environment: 
          SCAN_DEVICE: iPhone 7 Plus
          SCAN_SCHEME: WeeClik
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
  deploy:
    macos:
      xcode: "11.1.0"
    steps:
      - checkout
      - deploy:
          name: Deploy
          command: fastlane release_appstore

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            build-and-test
          filters:
            branches:
              only: release