# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

####### Before script #######

update_fastlane
default_platform(:ios)

####### Screenshot #######

desc "Generate new localized screenshots"
lane :screenshots do
  capture_screenshots(
    workspace: "WeeClik.xcworkspace", 
    scheme: "WeeClik"
  )
  upload_to_app_store(
    skip_binary_upload: true,
    skip_metadata: true
  )
end

####### Beta deployment #######

desc "Create Beta release"
lane :beta do
  changelog = prompt(
    text: "Changelog: ",
    multi_line_end_keyword: "END"
  )
  #sync_code_signing ## TODO: Set this using this link : https://docs.fastlane.tools/actions/sync_code_signing/
  build_app(
    scheme: "WeeClik",
    workspace: "WeeClik.xcworkspace"
  )
  upload_to_testflight(changelog: changelog)
end


####### Testing #######

desc "Runs all the tests"
lane :tests do
  unit_tests
  ui_tests
end

desc "Runs all unit tests"
lane :unit_tests do
  scan(
    workspace: "WeeClik.xcworkspace",
    scheme: "WeeClik",
    devices: ["iPhone 8 Plus"],
    clean: true
  )
end

desc "Runs all ui tests"
lane :ui_tests do
  scan(
    workspace: "WeeClik.xcworkspace",
    scheme: "WeeClik",
    devices: ["iPhone 8 Plus"],
    clean: true
  )
end
