//
//  StyleKitWeeclik.swift
//  Weeclik
//
//  Created by Herrick Wolber on 06/10/2019.
//  Copyright © 2019 Weeclik. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class StyleKitWeeclik : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawPartageGroupe_icon(frame: CGRect = CGRect(x: 0, y: 0, width: 240, height: 240), first: UIImage, second: UIImage) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }

        //// Color Declarations
        let white_color = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)


        //// Subframes
        let group: CGRect = CGRect(x: frame.minX + 10.5, y: frame.minY + 5, width: frame.width - 20.5, height: frame.height - 14)


        //// Group
        //// Second_image Drawing
        let second_imageRect = CGRect(x: group.minX + fastFloor(group.width * 0.18223 + 0.5), y: group.minY + fastFloor(group.height * 0.00000 + 0.5), width: fastFloor(group.width * 1.00000) - fastFloor(group.width * 0.18223 + 0.5) + 0.5, height: fastFloor(group.height * 0.79425) - fastFloor(group.height * 0.00000 + 0.5) + 0.5)
        let second_imagePath = UIBezierPath(ovalIn: second_imageRect)
        context.saveGState()
        second_imagePath.addClip()
        context.scaleBy(x: 1, y: -1)
        context.draw(second.cgImage!, in: CGRect(x: second_imageRect.minX - 120, y: -second_imageRect.minY + 120, width: second.size.width, height: second.size.height), byTiling: true)
        context.restoreGState()
        white_color.setStroke()
        second_imagePath.lineWidth = 4
        second_imagePath.stroke()


        //// First_image Drawing
        let first_imageRect = CGRect(x: group.minX + fastFloor(group.width * 0.00000 + 0.5), y: group.minY + fastFloor(group.height * 0.20575) + 0.5, width: fastFloor(group.width * 0.81777) - fastFloor(group.width * 0.00000 + 0.5) + 0.5, height: fastFloor(group.height * 1.00000 + 0.5) - fastFloor(group.height * 0.20575) - 0.5)
        let first_imagePath = UIBezierPath(ovalIn: first_imageRect)
        context.saveGState()
        first_imagePath.addClip()
        context.scaleBy(x: 1, y: -1)
        context.draw(first.cgImage!, in: CGRect(x: first_imageRect.minX - 120, y: -first_imageRect.minY + 120, width: first.size.width, height: first.size.height), byTiling: true)
        context.restoreGState()
        white_color.setStroke()
        first_imagePath.lineWidth = 4
        first_imagePath.stroke()
    }

    //// Generated Images

    @objc dynamic public class func imageOfPartageGroupe_icon(imageSize: CGSize = CGSize(width: 240, height: 240), first: UIImage, second: UIImage) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(imageSize, false, 0)
            StyleKitWeeclik.drawPartageGroupe_icon(frame: CGRect(x: 0, y: 0, width: imageSize.width, height: imageSize.height), first: first, second: second)

        let imageOfPartageGroupe_icon = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfPartageGroupe_icon
    }

}
